### ISSUE TITLE
The page takes a huge time to load when points are in a small area

### ISSUE THREAD

**Issue by AndersonSchmidt** [manubb/Leaflet.PixiOverlay#12]
This is the json with the points that I was trying to load: (Don't forget to change the file to .json)
[communes.txt](https://github.com/manubb/Leaflet.PixiOverlay/files/1766911/communes.txt)

**Comment by manubb** [comment]
Can you have a look at [this](https://manubb.github.io/Leaflet.PixiOverlay/issue-12.html) and tell me if the problem occurs?

**Comment by AndersonSchmidt** [comment]
Hey, first of all, thanks for your help. Yes, it's working very well. I saw that the problem is that I was using the "French Cities" example, and when I use the "US" example like you used in the link that you sent, the page loads really fast. But I still have some troubles. I need to load 500.000 points in that area. I changed the code to not animate the size of the points(now, each point has a static size) and it worked, the page load and it's "usable". But I need to get better performance, cause the page still "lagging". Do you know how to get better performance, maybe by deleting some process of the code?

**Comment by manubb** [comment]
In order to get better performance, you need to decrease the numbers of drawn pixel. This can be done by scaling down markers in low zoom levels (where many markers are drawn). You can have a look at this [demo](https://manubb.github.io/Leaflet.PixiOverlay/many-markers.html) where one million markers are displayed with a good user experience. (It is using `PIXI.ParticleContainer`. Note however that it has some bug when using with `doubleBuffering` option that will be fixed soon. See this [PR](https://github.com/pixijs/pixi.js/pull/4680).)

**Comment by AndersonSchmidt** [comment]
That's it!! It's working!
