### ISSUE TITLE
rescaling issues

### ISSUE THREAD

**Issue by sgentile** [manubb/Leaflet.PixiOverlay#5]
Both in your demo's and locally, the way the icons are positioned at times do not match their location.   ie. you can easily see markers in the water at zoom levels - as you zoom closer they are back on land where they belong.   

Is this something you are going to fix ?

**Comment by manubb** [comment]
I am not sure i understand the issue you are reporting. In demos on US and french cities, i use an algorithm that avoids marker overlaps and at lower zoom levels, the fact that marker are not at their precise location is expected. Can you post a screenshot displaying your problem?

**Comment by sgentile** [comment]
that explains it - I would like to disable that so that it's on the right latlng, ie. precision for what I need is more important than overlay at higher zoom levels.

what would you recommend I change to enable that ?

Thanks!

**Comment by sgentile** [comment]
Each of these represent the final city in the last image - as you can see,
it's not even close until zoomed in .  - If somone was wanting to know
where the city was, in the first example they would way off.




​

**Comment by manubb** [comment]
Here is a simplified version of us-cities demo:
https://manubb.github.io/Leaflet.PixiOverlay/us-cities-simple.html
that you can use as a base for what you want to do.

Note that the feature we are talking of is not a part of the main library ;-)

**Comment by sgentile** [comment]
Thanks Manuel - I'll check it out!

Appreciate your response

**Comment by sgentile** [comment]
That is exactly what I'm looking for!

What is your recommendation then for selection ?

I was thinking when an item is selected, return back all the markers at
that point.  What is your thought on that ?

**Comment by sgentile** [comment]
another thing I notice with this - the load time is significantly faster

**Comment by manubb** [comment]
Concerning selection, i cannot recommend anything as this is really app specific.

If the number of markers is small, you can simply use Pixi.js [interactivity](https://pixijs.github.io/examples/#/demos/interactivity.js).

If you want to display many markers you can have a look at the code of [us-cities demo](https://github.com/manubb/Leaflet.PixiOverlay/blob/master/docs/us-cities.html) to see how interactivity is implemented.
(I am using [quadtrees](https://github.com/d3/d3-quadtree) to find which marker(s) is(are) under the click or under the pointer. Since markers are static in your project, the code would be much simpler and you only need to use one quadtree.)

**Comment by manubb** [comment]
I'm gonna close this. Reopen if you need to.

**Comment by sgentile** [comment]
Thanks again for your help - I put a sample together for anyone else interested in trying this:

https://github.com/sgentile/PixieOverlaySample
