### ISSUE TITLE
Future plans?

### ISSUE THREAD

**Issue by leegee** [manubb/Leaflet.PixiOverlay#59]
Looking at the Million Marker demo.
When using the latest versions of Pixi and Leaflet, the ParticleContainer, I see the following error:

> Uncaught TypeError: Cannot set property '_parentID' of undefined
>    at ParticleContainer.Container.addChild (Container.ts:170)

I guess Pixi has moved on since your library was written -- are you considering rewriting with the PixiOverlay being a subclass of a Pixi container/something?

**Comment by manubb** [comment]
My patched particle container works with pixi@4 and i'm not expected it to work with pixi>4.Since this is not a part of the main lib, i'm not planning to update it. (No will and no time ;-)) 

The lib is fully compatible with pixi@5 but i did not test anything with pixi@6.

If anything is wrong with recent pixi@6, i'd be happy to review a PR!

**Comment by RoboVij** [comment]
Hi! I get the same error even with `"pixi.js": "4.8.8"`. Does your particleContainer patch come when I `npm install leaflet-pixi-overlay` or do I need to add a separate patch file to my code?
